### ISSUE TITLE
Net::Jupyter

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#121]
Module [Net::Jupyter](https://modules.perl6.org/dist/Net::Jupyter) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by JJ** [comment]
This one has a weird error during installation:
```
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/jmerelo/.rakudobrew/moar-2018.06/install/share/perl6/site/sources/AD7E59ADA2DC1BAAE651A41768A1F61ACFAA95D5 (Zef::Client) line 104
Use of uninitialized value @identities of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/jmerelo/.rakudobrew/moar-2018.06/install/share/perl6/site/sources/AD7E59ADA2DC1BAAE651A41768A1F61ACFAA95D5 (Zef::Client) line 117
===> Searching for missing dependencies: , Log::ZMQ, Digest::HMAC, Digest::SHA256::Native, UUID
No such method 'starts-with' for invocant of type 'Any'
```

**Comment by JJ** [comment]
I've created an issue, but it's possible that it's a problem with UUID. The problem is that `zef` errors are sometimes LTA so it's difficult to figure out what's exactly the problem.

**Comment by JJ** [comment]
Actually, #146

**Comment by JJ** [comment]
It's going to have the same problems as #146 too, so issued PR gabrielash/p6-net-jupyter#2
