### ISSUE TITLE
Math::Symbolic

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#136]
Module [Math::Symbolic](https://modules.perl6.org/dist/Math::Symbolic) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by AlexDaniel** [comment]
Uh! This one is a bit tough. One simple issue is that there's a missing `use MONKEY-SEE-NO-EVAL`, and here's a PR for that: https://github.com/raydiak/Math-Symbolic/pull/7

But that's not even close to make the module work again. If you try to run the tests you'll see this:
```
===SORRY!===
No such method 'key' for invocant of type 'Array'. Did you mean 'keys'?
```
No line number! And ``--ll-exception`` doesn't help, although maybe I'm blind.

Anyway, the issue is on [this line](https://github.com/raydiak/Math-Symbolic/blob/fe552292b60f568337c47f67659821fbaf480c45/lib/Math/Symbolic/Grammar.pm6#L44).

Doing something like:
```diff
  my %syn = %(
-     in => $%(%in{*}.map({@$_}).map: {.key => $_}),
+     in => $%(%in{*}.map({@$_}).map: {.[0].key => $_}),
      circ => $%(@circ.map: {.key => $_}),
      pre => $%(@pre.map: {.key => $_}),
      post => $%(@post.map: {.key => $_})
  );
```
makes it work a little better, but there's still something wrong and tests don't pass.

**Comment by nxadm** [comment]
Batpinging @bduggan and @danaj...

**Comment by raydiak** [comment]
Honestly I don't think this module ever fully caught up with the Great List Refactor in pre-Christmas days. I've spent the last few days cleaning up my bitrot across the ecosystem, and I'm saving this one for last as it's going to be a very large job bordering on a rewrite. I'm looking forward to working on it again in the immediate future, and will inform you here when this module is functional again.

**Comment by raydiak** [comment]
This module now passes all tests under current Rakudo versions

**Comment by jonathanstowe** [comment]
I think it may still have a problem with the META6.json:

```
Please note that a 'META6.json' file was found in '.', of which the 'provides' section was used to determine if a dependency is available or not.  Perhaps you need to add 'Math::Symbolic::Actions' in the <provides> section of that file?  Or need to specify a directory that does *not* have a 'META6.json' file?
```

**Comment by raydiak** [comment]
My bad, had only tested my local copy. Fixed and confirmed by re-testing a normal install through zef
