### ISSUE TITLE
Math::Model

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#139]
Module [Math::Model](https://modules.perl6.org/dist/Math::Model) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by moritz** [comment]
Works here with a not too-old rakudo version:

```
moritz@pete:~/p6/Math-Model$ perl6 --version
This is Rakudo version 2018.06-45-gddf496c built on MoarVM version 2018.06-34-g411f73f
implementing Perl 6.c.
moritz@pete:~/p6/Math-Model$ zef install .
===> Testing: Math::Model:ver<0.3>
# result: {:b($[0, 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3.0, 3.3, 3.6, 3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6.0]), :time($[0, 0.15, 0.3, 0.45, 0.6, 0.75, 0.9, 1.05, 1.2, 1.35, 1.5, 1.65, 1.8, 1.95, 2.1, 2.25, 2.4, 2.55, 2.7, 2.85, <3/1>])}
===> Testing [OK] for Math::Model:ver<0.3>
===> Installing: Math::Model:ver<0.3>
```

**Comment by Altai-man** [comment]
Failed with
`===> Install [SKIP] for Math::Model:ver<0.3>: Math::Model:ver<0.3>:auth<>:api<> already installed` which may be a toaster bug.
