### ISSUE TITLE
Log::ZMQ

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#146]
Module [Log::ZMQ](https://modules.perl6.org/dist/Log::ZMQ) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by JJ** [comment]
Works now after #116 was fixed.

**Comment by Altai-man** [comment]
Does not work for me:
```
➜  ~ zef install Log::ZMQ
===> Searching for: Log::ZMQ
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/koto/.perl6/sources/26B6EE127393E4686FC1F78170E52455F7135CE7 (Zef::Client) line 104
Use of uninitialized value @identities of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/koto/.perl6/sources/26B6EE127393E4686FC1F78170E52455F7135CE7 (Zef::Client) line 117
===> Searching for missing dependencies: 
No such method 'starts-with' for invocant of type 'Any'
```
The issue is that META specifies what Net::ZMQ should be installed in a way that is either wrong or not yet supported by zef at https://github.com/gabrielash/p6-log-zmq/blob/master/META6.json#L17.

**Comment by AlexDaniel** [comment]
@Altai-man there's a PR for that already by @ugexe++ https://github.com/gabrielash/p6-log-zmq/pull/5
