### ISSUE TITLE
Locale::Codes

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#147]
Module [Locale::Codes](https://modules.perl6.org/dist/Locale::Codes) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by Xliff** [comment]
This is weird. All tests pass, but I get the following during the installation:

```
$ zef install .  
===> Testing: Locale::Codes:ver<0.1.0>:auth<github:fayland>
===> Testing [OK] for Locale::Codes:ver<0.1.0>:auth<github:fayland>
===> Installing: Locale::Codes:ver<0.1.0>:auth<github:fayland>
===> Install [FAIL] for Locale::Codes:ver<0.1.0>:auth<github:fayland>: ===SORRY!===
Could not find Locale::Codes::Country_Codes at line 3 in:
    /home/cbwood/Projects/rakudobrew/moar-master/install/share/perl6/site
    /home/cbwood/Projects/rakudobrew/moar-master/install/share/perl6/vendor
    /home/cbwood/Projects/rakudobrew/moar-master/install/share/perl6
    CompUnit::Repository::AbsolutePath<94424015989776>
    CompUnit::Repository::NQP<94423994424416>
    CompUnit::Repository::Perl5<94423994424456>

===SORRY!===
Could not find Locale::Codes::Country_Codes at line 3 in:
    /home/cbwood/Projects/rakudobrew/moar-master/install/share/perl6/site
    /home/cbwood/Projects/rakudobrew/moar-master/install/share/perl6/vendor
    /home/cbwood/Projects/rakudobrew/moar-master/install/share/perl6
    CompUnit::Repository::AbsolutePath<94424015989776>
    CompUnit::Repository::NQP<94423994424416>
    CompUnit::Repository::Perl5<94423994424456>

```

**Comment by AlexDaniel** [comment]
@Xliff doesn't it mean that `provides` section should have missing files? https://github.com/fayland/perl6-Locale-Codes/blob/a409877561f183e3aad308e91a940305369488b6/META6.json#L8

**Comment by Xliff** [comment]
Why yes! Yes, it does!

**Comment by Xliff** [comment]
PR submitted as fayland/perl6-Locale-Codes#4
