### ISSUE TITLE
Lingua::EN::Stem::Porter

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#151]
Module [Lingua::EN::Stem::Porter](https://modules.perl6.org/dist/Lingua::EN::Stem::Porter) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by Altai-man** [comment]
https://webcache.googleusercontent.com/search?q=cache:vC-DEC2NgZAJ:https://github.com/johnspurr/Lingua-EN-Stem-Porter+&cd=1&hl=en&ct=clnk&gl=ua&lr=lang_en%7Clang_ru <- here is cached page.
For some reason author's account was deleted from GitHub, as well as all repositories, so I am removing the dead link from ecosystem.

**Comment by JJ** [comment]
The cache is no longer there. Did anyone obtain a copy? Are there forks out there?

**Comment by JJ** [comment]
[`samcv` has a copy](https://github.com/samcv/Lingua-EN-Stem-Porter). Maybe adopt it as a community module?

**Comment by JJ** [comment]
OK, [Added it back to the ecosystem](https://github.com/Raku/ecosystem/pull/501)
