### ISSUE TITLE
Inform

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#175]
Module [Inform](https://modules.perl6.org/dist/Inform) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by AlexDaniel** [comment]
This one depends on [Panda::Builder](https://github.com/finanalyst/p6-inform/blob/e5af4c04e7f5f6945bc4fbaab0842b263bb408c2/Build.pm#L1)

**Comment by JJ** [comment]
But it still does not work. Some problem with build. zef build really needs to say something meaningful when it fails, as well as let through "says" from build system, because I can't figure it out when it does not work why it does not. finanalyst/p6-inform#2

**Comment by JJ** [comment]
OK, I fixed the Build stuff. Thanks for the suggestion on using Build.

**Comment by finanalyst** [comment]
So much module related flooding on this list, it obscures problems.

An email to a developer responsible would be better than flooding the 
list which developers read.

Very poor community management.

**Comment by AlexDaniel** [comment]
> Very poor community management.

Thanks for the feedback!

This work was part of the [SQUASHathon](https://github.com/rakudo/rakudo/wiki/Monthly-Bug-Squash-Day) and you can read more about its organization [here](https://perl6.github.io/ecosystem-unbitrot/). As [mentioned in the weekly](https://p6weekly.wordpress.com/2018/08/06/2018-32-squashathon-done/), we managed to engage 29 contributors who helped with many modules in the ecosystem. With that amount of effort put in, it's unsurprising that there was a notification spam.

Seeing that perl 6 activity is ramping up, I think it's a good idea to [configure your notifications](https://github.com/settings/notifications) (e.g. “Automatically watch repositories” setting) in a way that fits you.
