### ISSUE TITLE
IO::CatHandle::AutoLines

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#186]
Module [IO::CatHandle::AutoLines](https://modules.perl6.org/dist/IO::CatHandle::AutoLines) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by AlexDaniel** [comment]
Hey @zoffixznet, wanna fix your module? :) FWIW it looks a bit rakudobuggy to me.

**Comment by zoffixznet** [comment]
> FWIW it looks a bit rakudobuggy to me.

Indeededly: https://github.com/rakudo/rakudo/issues/2174

**Comment by lizmat** [comment]
Fixed with https://github.com/rakudo/rakudo/commit/d09756ae66

**Comment by AlexDaniel** [comment]
Now it fails like this:
```
===> Testing: IO::CatHandle::AutoLines:ver<1.001002>
    #                      Got: 256
    # Does not smartmatch with: 0
```

**Comment by lizmat** [comment]
Trying to run the failing test manually, looks like it is producing the expected result.  Except that `$?` appears to be 1:

    $ perl6 -Ilib -e 'use IO::CatHandle::AutoLines; 42 does IO::CatHandle::AutoLines'
    IO::CatHandle::AutoLines can only be mixed into an IO::CatHandle
      in submethod TWEAK at /Users/liz/Github/perl6-IO-CatHandle-AutoLines/lib/IO/CatHandle/AutoLines.pm6 (IO::CatHandle::AutoLines) line 8
      in block <unit> at -e line 1
    $ echo $?
    1

**Comment by zoffixznet** [comment]
That one looks to be just an outdated test that was written before `Testo::is-run` started to default `status` check to `0` instead of `*`

[Fixed that](https://github.com/zoffixznet/perl6-IO-CatHandle-AutoLines/commit/62deb96acb2f00613503237adfd05ce0b7cb34b5) and now all tests pass.
