### ISSUE TITLE
Games::BubbleBreaker

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#209]
Module [Games::BubbleBreaker](https://modules.perl6.org/dist/Games::BubbleBreaker) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by Xliff** [comment]
There is an issue with libsdl on Debian based systems where libSDL.so is _not called_ libSDL.so, but a variety of names, dependent on the version. For example, the last version of libSDL version 1 is called libSDL-1.2.so, and libSDL version 2 is called libSDL2-2.0.so.

There is no way to resolve the dependency issue. 

Issue will be filed with the maintainer.

**Comment by AlexDaniel** [comment]
@Xliff but:
```bash
apt-file search libSDL.so
```
```
libsdl1.2-dev: /usr/lib/x86_64-linux-gnu/libSDL.so
```

---

```bash
apt-cache policy libsdl1.2-dev
```
```
libsdl1.2-dev:
  Installed: (none)
  Candidate: 1.2.15+dfsg2-1
  Version table:
     1.2.15+dfsg2-1 500
        500 http://deb.debian.org/debian sid/main amd64 Packages
        500 http://deb.debian.org/debian testing/main amd64 Packages
     1.2.15+dfsg1-4 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
     1.2.15-5 500
        500 http://deb.debian.org/debian wheezy/main amd64 Packages
```

**Comment by AlexDaniel** [comment]
PR sent: https://github.com/FROGGS/p6-Games-BubbleBreaker/pull/6
Unfortunately it doesn't run: https://github.com/FROGGS/p6-Games-BubbleBreaker/issues/7
