### ISSUE TITLE
DOM::Tiny

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#245]
Module [DOM::Tiny](https://modules.perl6.org/dist/DOM::Tiny) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by Altai-man** [comment]
Toast says:
`===> Install [SKIP] for DOM::Tiny:ver<0.4.0>:auth<github:zostay>: DOM::Tiny:ver<0.4.0>:auth<github:zostay>:api<> already installed`
which is odd, but otherwise the module installs fine.

**Comment by ronaldxs** [comment]
FWIW Toast is complaining about a version, 0.4.0, that seems to be more than three weeks old.  The current version is 0.4.1.  I don't see a date on the Eco Toaster UI but from the SQLite db time it looks like the toast was July 9, a few days before  the 0.4.1 release.  It might be helpful for the Toaster UI to show the timestamp and/or a commit id.

**Comment by Altai-man** [comment]
@ronaldxs could you please create an issue(feature request to be precise) at https://github.com/zoffixznet/perl6-Toaster repo? I think your message may get lost with current information flow.

**Comment by AlexDaniel** [comment]
Ninja'd :)
