### ISSUE TITLE
DBIx::NamedQueries

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#246]
Module [DBIx::NamedQueries](https://modules.perl6.org/dist/DBIx::NamedQueries) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by JJ** [comment]
Tests OK after some upstream change, probably

**Comment by AlexDaniel** [comment]
Fails here:
```
# Skipping author test. Set AUTHOR_TESTING to enable.
        # Failed test '.message matches Type check failed in binding to parameter '$obj_query'; expected DBIx::NamedQueries::Query but got Queries::Write::Failtest (Queries::Write::Failt...)'
        # at SETTING::src/core/Any-iterable-methods.pm6 line 634
        # Expected: Type check failed in binding to parameter '$obj_query'; expected DBIx::NamedQueries::Query but got Queries::Write::Failtest (Queries::Write::Failt...)
        # Got:      Type check failed in binding to parameter '$obj_query'; expected DBIx::NamedQueries::Query but got Queries::Write::Failtest (Queries::Write::Failtest.new)
        # Looks like you failed 1 test of 3
    # Failed test 'did we throws-like Exception?'
    # at t/04-query-fails.t line 25
    # Looks like you failed 1 test of 2
# Failed test 'create db subtests'
# at t/04-query-fails.t line 20
# Looks like you failed 1 test of 2
```

**Comment by JJ** [comment]
Right, I just realized I have 2018.03...

**Comment by JJ** [comment]
Sent "merge request" (GitLabese for "pull request): https://gitlab.com/mziescha/perl6-DBIx-NamedQueries/merge_requests/3

**Comment by AlexDaniel** [comment]
@JJ this change will make it fail on older rakudos

**Comment by AlexDaniel** [comment]
For example, testing for:

    /^‘Type check failed in binding to parameter '$obj_query'; expected DBIx::NamedQueries::Query but got Queries::Write::Failtest (Queries::Write::Failt’/

is going to work on all versions. But I'm not sure why it is needed to test the error message that precisely.

**Comment by JJ** [comment]
Ok, I'll change that
