### ISSUE TITLE
Crust

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#255]
Module [Crust](https://modules.perl6.org/dist/Crust) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by Altai-man** [comment]
Works fine after `HTTP::UserAgent` fix.

**Comment by AlexDaniel** [comment]
It is flapping:
```
# Failed test at t/Crust-Middleware/error-document.t line 80
    # expected: $["p6wx.errordocument.Content-Type" => "text/plain", :Content-Type("text/plain")]
    #      got: $[:Content-Type("text/plain"), "p6wx.errordocument.Content-Type" => "text/plain"]
    # Looks like you failed 1 test of 3
```

**Comment by JJ** [comment]
It's working for me with 2018.06

**Comment by jonathanstowe** [comment]
Doesn't it need something like:

```
diff --git a/t/Crust-Middleware/error-document.t b/t/Crust-Middleware/error-document.t
index dc4e127..804b5ab 100644
--- a/t/Crust-Middleware/error-document.t
+++ b/t/Crust-Middleware/error-document.t
@@ -77,7 +77,7 @@ subtest {
     my @ret = await $app(%env);
 
     is @ret[0], 500;
-    is-deeply @ret[1], ['p6wx.errordocument.Content-Type' => 'text/plain', :Content-Type('text/plain')];
+    is-deeply @ret[1].Hash, {'p6wx.errordocument.Content-Type' => 'text/plain', :Content-Type('text/plain')};
     isa-ok @ret[2], Array;
 }, 'Sub Request';
 
```
To be reliable?
