### ISSUE TITLE
Cro::HTTP

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#261]
Module [Cro::HTTP](https://modules.perl6.org/dist/Cro::HTTP) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by Altai-man** [comment]
There are some hangs around compiler or zef which are to be addressed, yet this particular module passes its test suite, usually installs and works fine.

**Comment by jonathanstowe** [comment]
```
===SORRY!===
Could not find Cro::BodyParserSelector at line 1 in:
    /home/jns/.zef/store/cro-http-0.8.0.tar.gz/cro-http-0.8.0
    /home/jns/.zef/store/cro-http-0.8.0.tar.gz/cro-http-0.8.0/lib
    /home/jns/.zef/store/P6-JSON-JWT.git/cf0dceb420aa7b62b2ff5509acddc6f3133e82c8/lib
    /home/jns/.zef/store/P6-Digest-HMAC.git/dcc292d77c7158eb7b53d3673cbee66d8b7b4fdf/lib
    /home/jns/.zef/store/libdigest-perl6.git/255c84d92247a10e4541684cd6a21eb171f37b1c/lib
    /home/jns/.perl6
    /home/jns/.rakudobrew/moar-master/install/share/perl6/site
    /home/jns/.rakudobrew/moar-master/install/share/perl6/vendor
    /home/jns/.rakudobrew/moar-master/install/share/perl6
    CompUnit::Repository::AbsolutePath<94453989381984>
    CompUnit::Repository::NQP<94453970209032>
    CompUnit::Repository::Perl5<94453970209072>
===SORRY!===
```

Looks like either an unstated dependency or it's missing from the ```provides```

**Comment by jonathanstowe** [comment]
Unstated dependency.
