### ISSUE TITLE
Bailador

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#279]
Module [Bailador](https://modules.perl6.org/dist/Bailador) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by Altai-man** [comment]
Just installed it fine as dependency for `Sparky::Plugin::Hello`:
```
===> Testing [OK] for Bailador:ver<0.0.15>:auth<github:Bailador>
===> Testing: Text::Markdown:ver<1.0.2>:auth<github:retupmoca>
===> Testing [OK] for Text::Markdown:ver<1.0.2>:auth<github:retupmoca>
===> Testing: Sparky:ver<0.0.24>
===> Testing [OK] for Sparky:ver<0.0.24>
===> Testing: Sparky::Plugin::Hello:ver<0.0.2>
===> Testing [OK] for Sparky::Plugin::Hello:ver<0.0.2>
===> Installing: NativeHelpers::Blob:ver<0.1.10>:auth<github:salortiz>
===> Installing: DBIish:ver<0.5.15>
===> Installing: JSON::Pretty:ver<0.1.0>:auth<github:FROGGS>
===> Installing: Config::INI
===> Installing: Config::Simple:auth<Sylvain Colinet>
===> Installing: Sparrowdo:ver<0.0.39>
===> Installing: Time::Crontab:ver<0.1.0>
===> Installing: HTTP::MultiPartParser
===> Installing: HTTP::Request::Supply:ver<0.1.1>:auth<github:zostay>
===> Installing: Path::Iterator:ver<0.0.1>:auth<Leon Timmermans>
===> Installing: HTTP::Server::Ogre:ver<0.0.3>
===> Installing: Log::Any:ver<0.9.4>
===> Installing: Template::Mojo:ver<.0.1>
===> Installing: Template::Mustache:ver<1.0.1>:auth<github:softmoth>
===> Installing: TAP::Harness:ver<0.0.3>:auth<Leon Timmermans>
===> Installing: Bailador:ver<0.0.15>:auth<github:Bailador>
===> Installing: Text::Markdown:ver<1.0.2>:auth<github:retupmoca>
===> Installing: Sparky:ver<0.0.24>
===> Installing: Sparky::Plugin::Hello:ver<0.0.2>

6 bin/ scripts [sparrowdo prove6 bailador sparky-web.pl6 sparkyd sparky-runner.pl6] installed to:
/home/koto/.perl6/bin
```
