### ISSUE TITLE
Amazon::DynamoDB

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#304]
Module [Amazon::DynamoDB](https://modules.perl6.org/dist/Amazon::DynamoDB) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by Altai-man** [comment]
`Aborting due to test failure: HTTP::UserAgent:ver<1.1.44>:auth<github:sergot> (use --force-test to override)`

**Comment by MattOates** [comment]
Actual problem assumes a directory in the home for tests that doesn't exist, and probably shouldn't be trying to use my aws credentials for a test anyway!:
`===> Testing: Amazon::DynamoDB:ver<0.1>:auth<github:zostay>
Failed to open file /Users/matt/.aws/credentials: No such file or directory
  in sub parse_file at /Users/matt/.zef/store/perl6-Config-INI.git/4e5494798dd0f8e73045cdb36d91302ba666410e/lib/Config/INI.pm (Config::INI) line 41
  in method get-credentials at /Users/matt/.zef/store/AWS-Session-0.4.tar.gz/AWS-Session-0.4/lib/AWS/Session.pm6 (AWS::Session) line 243
  in method load at /Users/matt/.zef/store/AWS-Session-0.4.tar.gz/AWS-Session-0.4/lib/AWS/Credentials.pm6 (AWS::Credentials) line 212
  in method load at /Users/matt/.zef/store/AWS-Session-0.4.tar.gz/AWS-Session-0.4/lib/AWS/Credentials.pm6 (AWS::Credentials) line 248
  in sub load-credentials at /Users/matt/.zef/store/AWS-Session-0.4.tar.gz/AWS-Session-0.4/lib/AWS/Credentials.pm6 (AWS::Credentials) line 265
  in method credentials at /Users/matt/.zef/store/Amazon-DynamoDB-0.1.tar.gz/Amazon-DynamoDB-0.1/lib/Amazon/DynamoDB.pm6 (Amazon::DynamoDB) line 756
  in method access-key at /Users/matt/.zef/store/Amazon-DynamoDB-0.1.tar.gz/Amazon-DynamoDB-0.1/lib/Amazon/DynamoDB.pm6 (Amazon::DynamoDB) line 760
  in method make-ddb-request at /Users/matt/.zef/store/Amazon-DynamoDB-0.1.tar.gz/Amazon-DynamoDB-0.1/lib/Amazon/DynamoDB.pm6 (Amazon::DynamoDB) line 785
  in method BatchGetItem at /Users/matt/.zef/store/Amazon-DynamoDB-0.1.tar.gz/Amazon-DynamoDB-0.1/lib/Amazon/DynamoDB.pm6 (Amazon::DynamoDB) line 847
  in block <unit> at t/aws-examples-offline.t line 57`

**Comment by MattOates** [comment]
Issue posted, bit too complex and opinionated to directly fix with a PR https://github.com/zostay/Amazon-DynamoDB/issues/1
