### ISSUE TITLE
API::USNavalObservatory

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#313]
Module [API::USNavalObservatory](https://modules.perl6.org/dist/API::USNavalObservatory) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by Altai-man** [comment]
`Aborting due to test failure: HTTP::UserAgent:ver<1.1.44>:auth<github:sergot> (use --force-test to override)`

**Comment by MattOates** [comment]
So I get Testing [OK] for HTTP::UserAgent:ver<1.1.44>:auth<github:sergot> thats without NETWORK_TESTING set. But get an actual fail on this module specifically:

```
===> Testing: API::USNavalObservatory:ver<1.0.0>:auth<github:cbk>
===SORRY!=== Error while compiling /Users/matt/.zef/store/API-USNavalObservatory.git/9761e7faf31aa31eddf994b3699db4efd88acbf3/lib/API/USNavalObservatory.pm6 (API::USNavalObservatory)
Variable '$dateeObj' is not declared. Did you mean '$dateObj'?
at /Users/matt/.zef/store/API-USNavalObservatory.git/9761e7faf31aa31eddf994b3699db4efd88acbf3/lib/API/USNavalObservatory.pm6 (API::USNavalObservatory):61
------>  "{ $dateObj.month }/{ $dateObj.day }/{ ⏏$dateeObj.year }";
===> Testing [FAIL]: API::USNavalObservatory:ver<1.0.0>:auth<github:cbk>
Aborting due to test failure: API::USNavalObservatory:ver<1.0.0>:auth<github:cbk> (use --force-test to override)
```

**Comment by Altai-man** [comment]
>Variable '$dateeObj' is not declared. Did you mean '$dateObj'?

Seems like a typo at https://github.com/cbk/API-USNavalObservatory/blob/master/lib/API/USNavalObservatory.pm6#L61
Can you sent a PR with this one fixed and if everything installs fine with this fix, close the issue?

**Comment by MattOates** [comment]
See above [^](https://github.com/cbk/API-USNavalObservatory/pull/2)

**Comment by Altai-man** [comment]
Thanks a lot. Please don't forget to add `PR sent` label when done.
