### ISSUE TITLE
Digest::MurmurHash3

### ISSUE THREAD

**Issue by Xliff** [perl6/ecosystem-unbitrot#315]
Fails building using latest rakudo

**Comment by Altai-man** [comment]
https://github.com/perl6/ecosystem-unbitrot/issues/235 <- original issue, so I am closing this one.
Thanks for participating. Please read the description of the issue and good luck. :+1:

**Comment by Xliff** [comment]
Rediscovered errors with building process. Investigating.

**Comment by Xliff** [comment]
Error is dependent on the 2018.04 version of Rakudo Star. When docker attempts to run the container, it fails doing:

```
RUN zef install     LibraryMake     NativeCall     Test     Test::META
```

This is most likely due to the fact that NativeCall is now included in Rakudo.

**Comment by Xliff** [comment]
Maintainer made changes. Module now installs properly.
