### ISSUE TITLE
`Db::Pg` and `epoll`

### ISSUE THREAD

**Issue by benjif** [perl6/ecosystem-unbitrot#316]
AlexDaniel opened an issue for this back in January, but it hasn't been fixed; it is causing both modules to fail: https://github.com/CurtTilmes/perl6-epoll/issues/2.

This is the test that fails (line 46): https://github.com/CurtTilmes/perl6-epoll/blob/master/t/02-multiple.t

**Comment by CurtTilmes** [comment]
I made the failing test optional  (I believe the failure is due to a broken test, not broken code).  The test always succeeds on my host.  It may be due to timing or something.

**Comment by AlexDaniel** [comment]
I think this can be closed now. Tickets are now automated.
