### ISSUE TITLE
AI::Agent

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#321]
Module [AI::Agent](https://modules.perl6.org/dist/AI::Agent) cannot be
installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not
  immediately).
* If you can **install the module without any problems**, add `works
  for me` label, leave a comment saying that it works for you and
  mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label,
  describe what you did to install it and ensure that same
  instructions are present in the README file of the module (otherwise
  submit a pull request).
* If the **module is broken**, try to fix it and send a PR. Add `PR
  sent` label.
* If there is a **problem in one of the dependencies**, add `failing
  dependency` label and write a comment explaining the situation. Feel
  free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're
  working on it (to make sure two or more people are not working on
  the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us
know on [#perl6 channel on freenode](https://perl6.org/irc) or just
leave a comment here. We will try to give you privileges as fast as
possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: AI::Agent
===> Found: AI::Agent:ver<0.2.7>:auth<CPAN:HOLYGHOST>:api<1> [via Zef::Repository::Ecosystems<cpan>]
===> Fetching [OK]: AI::Agent:ver<0.2.7>:auth<CPAN:HOLYGHOST>:api<1> to /home/alex/Blin/data/zef-data/tmp/1549579253.6326.1076/AI-Agent-0.2.7.tar.gz
===> Extraction [OK]: AI::Agent to /home/alex/Blin/data/zef-data/store/AI-Agent-0.2.7.tar.gz
===> Testing: AI::Agent:ver<0.2.7>:auth<CPAN:HOLYGHOST>:api<1>
Cannot modify an immutable 'Any' type object
  in method BUILD at /home/alex/Blin/data/zef-data/store/AI-Agent-0.2.7.tar.gz/AI-Agent/lib/AI/Agent/Agent.pm6 (AI::Agent::Agent) line 10
  in block <unit> at t/make-agent.t line 25

# Looks like you planned 2 tests, but ran 1
t/make-agent.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/2 subtests 

Test Summary Report
-------------------
t/make-agent.t (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 1.
Files=1, Tests=1,  5 wallclock secs ( 0.03 usr  0.00 sys +  3.24 cusr  0.22 csys =  3.49 CPU)
Result: FAIL
===> Testing [FAIL]: AI::Agent:ver<0.2.7>:auth<CPAN:HOLYGHOST>:api<1>
Failed to get passing tests, but continuing with --force-test
===> Installing: AI::Agent:ver<0.2.7>:auth<CPAN:HOLYGHOST>:api<1>
===> Install [OK] for AI::Agent:ver<0.2.7>:auth<CPAN:HOLYGHOST>:api<1>

````````````````````````````````````````````````````````

**Comment by JJ** [comment]
Besides not having proper tests, dependencies are badly expressed, I would simply eliminate it from the ecosystem.

**Comment by vendethiel** [comment]
seems like the module is not present anymore.

**Comment by JJ** [comment]
Closing, then.
