### ISSUE TITLE
Cache::Memcached

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#350]
Module [Cache::Memcached](https://modules.perl6.org/dist/Cache::Memcached) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Cache::Memcached
===> Found: Cache::Memcached:ver<0.0.11>:auth<cosimo> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Cache::Memcached:ver<0.0.11>:auth<cosimo> to /home/alex/Blin/data/zef-data/tmp/1549580818.20732.3167/perl6-cache-memcached.git
===> Extraction [OK]: Cache::Memcached to /home/alex/Blin/data/zef-data/store/perl6-cache-memcached.git
===> Testing: Cache::Memcached:ver<0.0.11>:auth<cosimo>
t/00050-meta.t ............... ok
t/00100-use.t ................ ok
t/00200-internals.t .......... ok
t/00300-connect.t ............ ok
t/00400-keys.t ............... ok
t/00500-stats.t .............. ok
t/00600-noreply.t ............ ok
t/00700-reconnect-timeout.t .. ok
t/00800-utf8-key.t ........... ok
A plan is required in order to use skip-rest
  in sub skip-rest at /tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/sources/2D4A7CA10695CD2B374573413D261A660E282E2A (Test) line 399
  in block <unit> at t/00900-associative.t line 12

t/00900-associative.t ........ 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

Test Summary Report
-------------------
t/00900-associative.t      (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=10, Tests=81, 15 wallclock secs ( 0.06 usr  0.02 sys + 14.08 cusr  0.87 csys = 15.03 CPU)
Result: FAIL
===> Testing [FAIL]: Cache::Memcached:ver<0.0.11>:auth<cosimo>
Failed to get passing tests, but continuing with --force-test
===> Installing: Cache::Memcached:ver<0.0.11>:auth<cosimo>
===> Install [OK] for Cache::Memcached:ver<0.0.11>:auth<cosimo>

````````````````````````````````````````````````````````

Ping @cosimo

**Comment by jonathanstowe** [comment]
My fault.  Had been p[anning to remove the associative stuff anyway.

**Comment by jonathanstowe** [comment]
There seems to be a thing where ```zef```  is slightly less tolerant of TAP issues than other tools. 

I'm going to remove this test altogether and remove the feature (which was dumb,) at some point in the future.

**Comment by jonathanstowe** [comment]
I think this is cool now.  I m just waiting on Travis.

**Comment by jonathanstowe** [comment]
Yeah that's cool now.  Imma close it.
