### ISSUE TITLE
Crypt::TweetNacl

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#368]
Module [Crypt::TweetNacl](https://modules.perl6.org/dist/Crypt::TweetNacl) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Crypt::TweetNacl
===> Found: Crypt::TweetNacl:ver<0.0.3> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Crypt::TweetNacl:ver<0.0.3> to /home/alex/Blin/data/zef-data/tmp/1549581967.21638.3930/perl6-tweetnacl.git
===> Extraction [OK]: Crypt::TweetNacl to /home/alex/Blin/data/zef-data/store/perl6-tweetnacl.git
===> Building: Crypt::TweetNacl:ver<0.0.3>
Command: /tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/bin/perl6 -Ilib -e require '/home/alex/Blin/data/zef-data/store/perl6-tweetnacl.git/8bcf5477a6f445a0abb3f2ee3f77fb65c5561a12/Build.pm'; ::('Build').new.build('/home/alex/Blin/data/zef-data/store/perl6-tweetnacl.git/8bcf5477a6f445a0abb3f2ee3f77fb65c5561a12') ?? exit(0) !! exit(1);
gcc -c -fPIC -Werror=declaration-after-statement -Werror=pointer-arith -O3 -DNDEBUG  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -o  tweetnacl.o tweetnacl/src/tweetnacl.c
gcc -c -fPIC -Werror=declaration-after-statement -Werror=pointer-arith -O3 -DNDEBUG  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -o  devurandom.o tweetnacl/contrib/randombytes/devurandom.c
gcc -shared -fPIC  -O3 -DNDEBUG -Wl,-rpath,"//tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/lib"  -lm -lpthread -lrt -ldl -o /home/alex/Blin/data/zef-data/store/perl6-tweetnacl.git/8bcf5477a6f445a0abb3f2ee3f77fb65c5561a12/resources/libraries/libtweetnacl.so tweetnacl.o devurandom.o
===> Building [OK] for Crypt::TweetNacl:ver<0.0.3>
===> Testing: Crypt::TweetNacl:ver<0.0.3>
t/00-load.t ............... ok
Cannot resolve caller STORE(Buf:D: NativeCall::Types::CArray[uint8]:D, :INITIALIZE); none of these signatures match:
    (Buf:D: Blob:D $blob, *%_)
    (Buf:D: int @values, *%_)
    (Buf:D: Iterable:D \iterable, *%_)
    (Blob:D: Iterable:D \iterable, :$INITIALIZE, *%_)
  in submethod BUILD at /home/alex/Blin/data/zef-data/store/perl6-tweetnacl.git/8bcf5477a6f445a0abb3f2ee3f77fb65c5561a12/lib/Crypt/TweetNacl/Basics.pm6 (Crypt::TweetNacl::Basics) line 35
  in block <unit> at t/01-basic.t line 17

# Looks like you planned 5 tests, but ran 4
t/01-basic.t .............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/5 subtests 
t/02-random.t ............. ok
t/03-crypto_box.t ......... ok
t/04-box.t ................ ok
t/05-helpers.t ............ ok
t/06-sign.t ............... ok
t/07-crypto_secret_box.t .. ok
t/08-CryptoSecretBox.t .... ok

Test Summary Report
-------------------
t/01-basic.t            (Wstat: 65280 Tests: 4 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 5 tests but ran 4.
Files=9, Tests=34, 26 wallclock secs ( 0.04 usr  0.02 sys + 20.71 cusr  1.13 csys = 21.90 CPU)
Result: FAIL
===> Testing [FAIL]: Crypt::TweetNacl:ver<0.0.3>
Failed to get passing tests, but continuing with --force-test
===> Installing: Crypt::TweetNacl:ver<0.0.3>
===> Install [OK] for Crypt::TweetNacl:ver<0.0.3>

````````````````````````````````````````````````````````

Ping @soundart

**Comment by AlexDaniel** [comment]
Turns out to be a rakudobug: https://github.com/rakudo/rakudo/issues/2681

**Comment by lizmat** [comment]
Rakudobug fixed with https://github.com/rakudo/rakudo/commit/ada116ef99 .  Module installs cleanly again.
