### ISSUE TITLE
GLFW

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#400]
Module [GLFW](https://modules.perl6.org/dist/GLFW) cannot be installed (`Flapper`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: GLFW
===SORRY!===
Could not find GLFW::VidMode at line 7 in:
    inst#/home/alex/Blin/installed/GLFW_0.1.0
    file#/home/alex/Blin/data/zef/lib
    inst#/home/alex/.perl6
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/site
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/vendor
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6
    ap#
    nqp#
    perl5#

===> Found: GLFW:ver<0.1.0> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: GLFW:ver<0.1.0> to /home/alex/Blin/data/zef-data/tmp/1549580424.11408.252/p6-GLFW.git
===> Extraction [OK]: GLFW to /home/alex/Blin/data/zef-data/store/p6-GLFW.git
===> Testing: GLFW:ver<0.1.0>
===> Testing [OK] for GLFW:ver<0.1.0>
===> Installing: GLFW:ver<0.1.0>
===> Install [FAIL] for GLFW:ver<0.1.0>: ===SORRY!===
Could not find GLFW::VidMode at line 7 in:
    inst#/home/alex/Blin/installed/GLFW_0.1.0
    file#/home/alex/Blin/data/zef/lib
    inst#/home/alex/.perl6
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/site
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/vendor
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6
    ap#
    nqp#
    perl5#


````````````````````````````````````````````````````````

Ping @YellowApple

Previous ticket: #211

**Comment by YellowApple** [comment]
Hmmm.

The error doesn't seem to include an actual filename, but I'm assuming the "line 7" here is [the one in `lib/GLFW/Monitor.pm6`](https://github.com/YellowApple/p6-GLFW/blob/b211bbde816796d16cee12180942004f71a77eb6/lib/GLFW/Monitor.pm6#L7), which is indeed a call to `need GLFW::VidMode`.

Not sure why this is throwing an error, though (it wasn't before), given that `lib/GLFW/VidMode.pm6` exists.  Is something wonky with the module path y'all are using?  Or maybe something changed in how Perl6 searches for modules?

**Comment by jonathanstowe** [comment]
The ```lib/GLFW/VidMode.pm6``` needs to be in the ```provides```

**Comment by YellowApple** [comment]
Yep, that'd do it.  Weird that it wasn't a problem before (or at least not one I noticed previously when testing its installability).  Should be fixed now.  Thanks!
