### ISSUE TITLE
HTML::Canvas

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#412]
Module [HTML::Canvas](https://modules.perl6.org/dist/HTML::Canvas) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: HTML::Canvas
===> Found: HTML::Canvas:ver<0.0.5>:auth<github:p6-css>:api<2dcontext-20151119> [via Zef::Repository::Ecosystems<cpan>]
===> Fetching [OK]: HTML::Canvas:ver<0.0.5>:auth<github:p6-css>:api<2dcontext-20151119> to /home/alex/Blin/data/zef-data/tmp/1549584007.3408.8372/HTML-Canvas-0.0.5.tar.gz
===> Extraction [OK]: HTML::Canvas to /home/alex/Blin/data/zef-data/store/HTML-Canvas-0.0.5.tar.gz
===> Testing: HTML::Canvas:ver<0.0.5>:auth<github:p6-css>:api<2dcontext-20151119>
t/00-readme.t ............... ok
t/01-basic.t ................ ok
t/cairo-transforms.t ........ ok
t/images.t .................. ok
Unable to parse the pattern

stopped on image 1: unable to resolve font-name: courier:weight=bold
  in block  at t/render-pdf-test-sheets.t line 38
# Failed test 'completion of image 1'
# at t/render-pdf-test-sheets.t line 48
Unable to parse the pattern

stopped on image 2: unable to resolve font-name: arial:weight=bold
  in block  at t/render-pdf-test-sheets.t line 38
# Failed test 'completion of image 2'
# at t/render-pdf-test-sheets.t line 48
Unable to parse the pattern

stopped on image 8: unable to resolve font-name: courier:weight=bold
  in block  at t/render-pdf-test-sheets.t line 38
# Failed test 'completion of image 8'
# at t/render-pdf-test-sheets.t line 48
# Looks like you failed 3 tests of 13
t/render-pdf-test-sheets.t .. 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/13 subtests 
t/render-png-basic.t ........ ok
t/transforms.t .............. ok

Test Summary Report
-------------------
t/render-pdf-test-sheets.t (Wstat: 768 Tests: 13 Failed: 3)
  Failed tests:  1, 3, 9
  Non-zero exit status: 3
Files=7, Tests=54, 29 wallclock secs ( 0.05 usr  0.01 sys + 39.58 cusr  3.73 csys = 43.37 CPU)
Result: FAIL
===> Testing [FAIL]: HTML::Canvas:ver<0.0.5>:auth<github:p6-css>:api<2dcontext-20151119>
Failed to get passing tests, but continuing with --force-test
===> Installing: HTML::Canvas:ver<0.0.5>:auth<github:p6-css>:api<2dcontext-20151119>
===> Install [OK] for HTML::Canvas:ver<0.0.5>:auth<github:p6-css>:api<2dcontext-20151119>

````````````````````````````````````````````````````````

Ping @p6-css

Previous ticket: #199

**Comment by dwarring** [comment]
Unable to find some fonts, which is causing test failures.

**Comment by AlexDaniel** [comment]
@dwarring is there something I should install to make it pass?

**Comment by dwarring** [comment]
@AlexDaniel you could try gsfonts.

**Comment by dwarring** [comment]
Sorry, on my Debian system it's actually finding fonts from fonts-dejavu-core:
```
% fc-match -f '%{file}\n' ariel:weight=bold
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
% dpkg-query -S /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
fonts-dejavu-core: /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
```
so that package might be the one that's needed.

**Comment by AlexDaniel** [comment]
Ah-ha, OK, I'll try that, if it works the issue will be closed. I added `native dependency` label because there's no better label… Thanks!

**Comment by dwarring** [comment]
Btw, HTML::Canvas is using the `font-font` method from [CSS::Properties::Font](https://github.com/p6-css/CSS-Properties-p6/blob/master/lib/CSS/Properties/Font.pm) which just run an `fc-match` shell-command as above.

**Comment by dwarring** [comment]
I'll also update the README. Seems the module needs some fonts to be installed.

**Comment by dwarring** [comment]
dang! arial, not ariel: `% fc-match -f '%{file}\n' arial:weight=bold`. Which finds a font from a different package: font-liberation.
```
% fc-match -f '%{file}\n' arial:weight=bold
/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf
% dpkg-query -S /usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf
fonts-liberation: /usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf
```
As long as fc-match can find both 'courier:weight=bold' and 'arial:weight=bold'

**Comment by dwarring** [comment]
I've add a monospace font to the module's resources, which is used as a fallback when fc-match fails to find a font. Should ease automated testing and initial install of this module.

Readme also updated.

Uploaded to CPAN as HTML::Canvas 0.0.6

**Comment by AlexDaniel** [comment]
@dwarring thank you!
