### ISSUE TITLE
Hydrate

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#423]
Module [Hydrate](https://modules.perl6.org/dist/Hydrate) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Hydrate
===> Found: Hydrate:auth<vendethiel> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Hydrate:auth<vendethiel> to /home/alex/Blin/data/zef-data/tmp/1549580034.29203.2530/hydrate6.git
===> Extraction [OK]: Hydrate to /home/alex/Blin/data/zef-data/store/hydrate6.git
===> Testing: Hydrate:auth<vendethiel>
Type check failed in binding to parameter '<anon>'; expected Any but got Mu (Mu)
  in block  at /home/alex/Blin/data/zef-data/store/hydrate6.git/b8e596b31aff58546eea6eca2d1e874f4df9f9cb/lib/Hydrate.pm (Hydrate) line 20
  in sub value-for at /home/alex/Blin/data/zef-data/store/hydrate6.git/b8e596b31aff58546eea6eca2d1e874f4df9f9cb/lib/Hydrate.pm (Hydrate) line 17
  in block  at /home/alex/Blin/data/zef-data/store/hydrate6.git/b8e596b31aff58546eea6eca2d1e874f4df9f9cb/lib/Hydrate.pm (Hydrate) line 44
  in sub hydrate at /home/alex/Blin/data/zef-data/store/hydrate6.git/b8e596b31aff58546eea6eca2d1e874f4df9f9cb/lib/Hydrate.pm (Hydrate) line 40
  in block <unit> at t/01-basic.t line 14

t/01-basic.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

Test Summary Report
-------------------
t/01-basic.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  3 wallclock secs ( 0.02 usr  0.00 sys +  1.76 cusr  0.14 csys =  1.92 CPU)
Result: FAIL
===> Testing [FAIL]: Hydrate:auth<vendethiel>
Failed to get passing tests, but continuing with --force-test
===> Installing: Hydrate:auth<vendethiel>
===> Install [OK] for Hydrate:auth<vendethiel>

````````````````````````````````````````````````````````

Ping @vendethiel

Previous ticket: #187

**Comment by vendethiel** [comment]
also: vendethiel/hydrate6#2

**Comment by vendethiel** [comment]
Seems like `type<>` broke for `Mu`:

```
> Mu<>
Type check failed in binding to parameter '<anon>'; expected Any but got Mu (Mu)
  in block <unit> at <unknown file> line 1
```

it's the crux of the issue. Is it supposed to be that way?

**Comment by AlexDaniel** [comment]
* Bisected: (2018-04-21) https://github.com/rakudo/rakudo/commit/4b5d36f3a8dff65cb41d4c3747c3f15e6fa36cbb
* Output before and after: https://gist.github.com/2077ce45814f1ad0304b35266bb52bc9

Does that make sense?

**Comment by vendethiel** [comment]
I understand what happened. I'm asking whether it's intended to be so, and how I can decontainerize (without ressorting to nqp) without it.

**Comment by vendethiel** [comment]
Fixed at some point.
