### ISSUE TITLE
Test::HTTP::Server

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#43]
Module [Test::HTTP::Server](https://modules.perl6.org/dist/Test::HTTP::Server) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by JJ** [comment]
I get this error:
```
===> Testing: Test::HTTP::Server:ver<0.1.0>
Could not connect socket: Connection refused
  in method get-connection at /home/jmerelo/.rakudobrew/moar-2018.06/install/share/perl6/site/sources/F606E8EB426689DEE80E98DA5CCF54C1C10D8DD8 (HTTP::UserAgent) line 373
  in method get-connection at /home/jmerelo/.rakudobrew/moar-2018.06/install/share/perl6/site/sources/F606E8EB426689DEE80E98DA5CCF54C1C10D8DD8 (HTTP::UserAgent) line 359
  in method request at /home/jmerelo/.rakudobrew/moar-2018.06/install/share/perl6/site/sources/F606E8EB426689DEE80E98DA5CCF54C1C10D8DD8 (HTTP::UserAgent) line 156
  in method get at /home/jmerelo/.rakudobrew/moar-2018.06/install/share/perl6/site/sources/F606E8EB426689DEE80E98DA5CCF54C1C10D8DD8 (HTTP::UserAgent) line 102
  in method get at /home/jmerelo/.rakudobrew/moar-2018.06/install/share/perl6/site/sources/F606E8EB426689DEE80E98DA5CCF54C1C10D8DD8 (HTTP::UserAgent) line 105
  in block <unit> at t/03-empty-folder.t line 22
```
I'll create an issue

**Comment by JJ** [comment]
Sent PR: Scimon/p6-Test-HTTP-Server#2
