### ISSUE TITLE
JSON::RPC

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#440]
Module [JSON::RPC](https://modules.perl6.org/dist/JSON::RPC) cannot be installed (`Fail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: JSON::RPC
===> Found: JSON::RPC:ver<1.0.0>:auth<bbkr> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: JSON::RPC:ver<1.0.0>:auth<bbkr> to /home/alex/Blin/data/zef-data/tmp/1549582137.26124.5581/jsonrpc.git
===> Extraction [OK]: JSON::RPC to /home/alex/Blin/data/zef-data/store/jsonrpc.git
===> Testing: JSON::RPC:ver<1.0.0>:auth<bbkr>
getlex: outer index out of range
  in block  at /home/alex/Blin/data/zef-data/store/jsonrpc.git/3b4797efc92d501fa5d5a3198457b7c16e091f7d/lib/JSON/RPC/Client.pm6 (JSON::RPC::Client) line 27
  in block <unit> at t/00-client.t line 19

t/00-client.t ....... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 39/39 subtests 
t/01-server.t ....... ok
t/99-author-meta.t .. ok

Test Summary Report
-------------------
t/00-client.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 39 tests but ran 0.
Files=3, Tests=30, 18 wallclock secs ( 0.05 usr  0.00 sys + 14.39 cusr  0.64 csys = 15.08 CPU)
Result: FAIL
===> Testing [FAIL]: JSON::RPC:ver<1.0.0>:auth<bbkr>
Failed to get passing tests, but continuing with --force-test
===> Installing: JSON::RPC:ver<1.0.0>:auth<bbkr>
===> Install [OK] for JSON::RPC:ver<1.0.0>:auth<bbkr>

````````````````````````````````````````````````````````

Ping @bbkr

Previous ticket: #164

**Comment by bbkr** [comment]
Rakudo fix resolved the issue. Tests are passing now.
