### ISSUE TITLE
Jupyter::Kernel

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#444]
Module [Jupyter::Kernel](https://modules.perl6.org/dist/Jupyter::Kernel) cannot be installed (`Flapper`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Jupyter::Kernel
===> Found: Jupyter::Kernel:ver<0.0.9> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Jupyter::Kernel:ver<0.0.9> to /home/alex/Blin/data/zef-data/tmp/1549582410.32505.5318/p6-jupyter-kernel.git
===> Extraction [OK]: Jupyter::Kernel to /home/alex/Blin/data/zef-data/store/p6-jupyter-kernel.git
===> Testing: Jupyter::Kernel:ver<0.0.9>
t/01-basic.t ......... 
Failed 1/1 subtests 
t/02-sandbox.t ....... ok
t/03-service.t ....... ok
t/04-completions.t ... skipped: Set P6_JUPYTER_TEST_AUTOCOMPLETE to run these
t/05-autocomplete.t .. ok
t/06-magic.t ......... ok
t/07-comms.t ......... ok
t/99-meta.t .......... ok

Test Summary Report
-------------------
t/01-basic.t       (Wstat: 11 Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=8, Tests=144, 58 wallclock secs ( 0.07 usr  0.01 sys + 49.80 cusr  1.82 csys = 51.70 CPU)
Result: FAIL
===> Testing [FAIL]: Jupyter::Kernel:ver<0.0.9>
Failed to get passing tests, but continuing with --force-test
===> Installing: Jupyter::Kernel:ver<0.0.9>
===> Install [OK] for Jupyter::Kernel:ver<0.0.9>

1 bin/ script [jupyter-kernel.p6] installed to:
/home/alex/Blin/installed/Jupyter::Kernel_0.0.9/bin

````````````````````````````````````````````````````````

Ping @bduggan

Previous ticket: #160

**Comment by bduggan** [comment]
I see this is closed but I'll comment anyway -- I couldn't reproduce this -- looks like maybe it's just that the first run takes too long (precompilation?)

**Comment by AlexDaniel** [comment]
@bduggan this is an actual issue and it was closed by “mistake”. In the OP it says that the status is `Flapper`, meaning that it succeeds sometimes but other times it fails. It was closed because on the most recent run in succeeded (just luck), so it was closed automatically.

> looks like maybe it's just that the first run takes too long (precompilation?)

No. It segfaulted. See this:
```
  Non-zero wait status: 11
```
That's a segfault. I don't know if there's an issue with Rakudo or with this module, but it's not OK.

**Comment by AlexDaniel** [comment]
Also, if you have troubles reproducing this, I recommend something like:

```bash
time while PERL6LIB=lib/ prove --exec=perl6 t/; do :; done
```
That is, keep running the tests until it fails.
