### ISSUE TITLE
Locale-Codes-Country

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#455]
Module [Locale-Codes-Country](https://modules.perl6.org/dist/Locale-Codes-Country) cannot be installed (`Flapper`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Locale-Codes-Country
[31m===[0mSORRY![31m===[0m Error while compiling /home/alex/Blin/installed/Locale-Codes-Country_1.0.0/sources/748E2CD905ABAE0827AACEEB7D7FA84FF39281D5 (Locale::Codes::Country)
Too late to switch language version. Must be used as the very first statement.
at /home/alex/Blin/installed/Locale-Codes-Country_1.0.0/sources/748E2CD905ABAE0827AACEEB7D7FA84FF39281D5 (Locale::Codes::Country):2
------> [32muse v6[33m⏏[31m;[0m

===> Found: Locale-Codes-Country:ver<1.0.0>:auth<Dean Powell> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Locale-Codes-Country:ver<1.0.0>:auth<Dean Powell> to /home/alex/Blin/data/zef-data/tmp/1549579416.10493.3552/Locale-Codes-Country.git
===> Extraction [OK]: Locale-Codes-Country to /home/alex/Blin/data/zef-data/store/Locale-Codes-Country.git
===> Testing: Locale-Codes-Country:ver<1.0.0>:auth<Dean Powell>
===> Testing [OK] for Locale-Codes-Country:ver<1.0.0>:auth<Dean Powell>
===> Installing: Locale-Codes-Country:ver<1.0.0>:auth<Dean Powell>
===> Install [FAIL] for Locale-Codes-Country:ver<1.0.0>:auth<Dean Powell>: [31m===[0mSORRY![31m===[0m Error while compiling /home/alex/Blin/installed/Locale-Codes-Country_1.0.0/sources/748E2CD905ABAE0827AACEEB7D7FA84FF39281D5 (Locale::Codes::Country)
Too late to switch language version. Must be used as the very first statement.
at /home/alex/Blin/installed/Locale-Codes-Country_1.0.0/sources/748E2CD905ABAE0827AACEEB7D7FA84FF39281D5 (Locale::Codes::Country):2
------> [32muse v6[33m⏏[31m;[0m


````````````````````````````````````````````````````````

Ping @PowellDean

**Comment by PowellDean** [comment]
Hi:

Thanks for the ping. I've just installed the module from scratch from a command line: 'zef install Locale-Codes-Country.' Install went without issue, and I'm able to call the various subroutines as expected. My machine is Windows 10, using Rakudo Star version 2018.04.1, implementing v6.c.

Not sure what the 'Too late to switch language version...' message refers to but I'll dig into it.

Regards,
Dean Powell

**Comment by AlexDaniel** [comment]
@PowellDean Ah, that's is a relatively recent change. 2018.04 still allows `use v` lines to be anywhere, so you need a newer rakudo version to reproduce.

Basicaly just move this line to the top of the file:
https://github.com/PowellDean/Locale-Codes-Country/blob/1b6e903b95769a905c73899302797453665ffd1b/lib/Locale/Codes/Country.pm6#L2

**Comment by PowellDean** [comment]
@AlexDaniel Fixed and pushed. Many thanks for the spot and the fix. I appreciate the help. I'd update the ticket but it appears I lack permissions to do so. If you wish, grant me appropriate privileges so I can update the ticket, or if it's less work go ahead and close.

**Comment by AlexDaniel** [comment]
@PowellDean Thank you! I've sent you an invitation, you can accept it here: https://github.com/perl6. The issue will be closed automatically when the time comes :)
