### ISSUE TITLE
Lumberjack

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#458]
Module [Lumberjack](https://modules.perl6.org/dist/Lumberjack) cannot be installed (`Flapper`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Lumberjack
===SORRY!===
Serialization Error: missing static code ref for closure '' (src/Perl6/World.nqp:2453)

===> Found: Lumberjack:ver<0.0.7>:auth<github:jonathanstowe>:api<1.0> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Lumberjack:ver<0.0.7>:auth<github:jonathanstowe>:api<1.0> to /home/alex/Blin/data/zef-data/tmp/1549581061.26191.9433/Lumberjack.git
===> Extraction [OK]: Lumberjack to /home/alex/Blin/data/zef-data/store/Lumberjack.git
===> Testing: Lumberjack:ver<0.0.7>:auth<github:jonathanstowe>:api<1.0>
t/001-meta.t ................ ok
# Failed test 'Can use Lumberjack module'
# at t/010-basic.t line 6
# ===SORRY!===
# Serialization Error: missing static code ref for closure '' (src/Perl6/World.nqp:2453)
# 
# Looks like you failed 1 test of 1
t/010-basic.t ............... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
t/020-class.t ............... ok
t/030-simple.t .............. ok
t/040-dispatcher-basic.t .... ok
t/050-formatter.t ........... ok
t/060-dispatcher-console.t .. ok
t/070-dispatcher-file.t ..... ok

Test Summary Report
-------------------
t/010-basic.t             (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=8, Tests=185, 44 wallclock secs ( 0.07 usr  0.01 sys + 40.84 cusr  1.29 csys = 42.21 CPU)
Result: FAIL
===> Testing [FAIL]: Lumberjack:ver<0.0.7>:auth<github:jonathanstowe>:api<1.0>
Failed to get passing tests, but continuing with --force-test
===> Installing: Lumberjack:ver<0.0.7>:auth<github:jonathanstowe>:api<1.0>
===> Install [FAIL] for Lumberjack:ver<0.0.7>:auth<github:jonathanstowe>:api<1.0>: ===SORRY!===
Serialization Error: missing static code ref for closure '' (src/Perl6/World.nqp:2453)


````````````````````````````````````````````````````````

Ping @jonathanstowe

**Comment by jonathanstowe** [comment]
Same rakudo bug.  You may note that if you run the tests again it will work fine,

**Comment by AlexDaniel** [comment]
I assume https://github.com/perl6/ecosystem-unbitrot/issues/460

**Comment by jonathanstowe** [comment]
I had an unfounded faith in the inexhorable progress of Rakudo ;-)  I'll roll back the change that assumed the precompilation bug was actually fixed.

**Comment by jonathanstowe** [comment]
The above commit reverts the change that broke it, uploaded v0.0.8 to CPAN

**Comment by jonathanstowe** [comment]
Ignore the travis failure that was just me being somewhat hungover.
