### ISSUE TITLE
Lumberjack::Dispatcher::Syslog

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#460]
Module [Lumberjack::Dispatcher::Syslog](https://modules.perl6.org/dist/Lumberjack::Dispatcher::Syslog) cannot be installed (`Flapper`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Lumberjack::Dispatcher::Syslog
===SORRY!===
Serialization Error: missing static code ref for closure '' (src/Perl6/World.nqp:2453)

===> Found: Lumberjack::Dispatcher::Syslog:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0> [via Zef::Repository::Ecosystems<cpan>]
===> Fetching [OK]: Lumberjack::Dispatcher::Syslog:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0> to /home/alex/Blin/data/zef-data/tmp/1549581744.15858.9260/Lumberjack-Dispatcher-Syslog-0.0.3.tar.gz
===> Extraction [OK]: Lumberjack::Dispatcher::Syslog to /home/alex/Blin/data/zef-data/store/Lumberjack-Dispatcher-Syslog-0.0.3.tar.gz
===> Testing: Lumberjack::Dispatcher::Syslog:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>
t/001-meta.t ........ ok
# Failed test 'can load the module'
# at t/010-use.t line 7
# ===SORRY!===
# Serialization Error: missing static code ref for closure '' (src/Perl6/World.nqp:2453)
# 
# Looks like you failed 1 test of 1
t/010-use.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
t/020-dispatcher.t .. ok

Test Summary Report
-------------------
t/010-use.t       (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=3, Tests=8, 23 wallclock secs ( 0.04 usr  0.01 sys + 18.84 cusr  0.64 csys = 19.53 CPU)
Result: FAIL
===> Testing [FAIL]: Lumberjack::Dispatcher::Syslog:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>
Failed to get passing tests, but continuing with --force-test
===> Installing: Lumberjack::Dispatcher::Syslog:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>
===> Install [FAIL] for Lumberjack::Dispatcher::Syslog:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>: ===SORRY!===
Serialization Error: missing static code ref for closure '' (src/Perl6/World.nqp:2453)


````````````````````````````````````````````````````````

Ping @jonathanstowe

**Comment by jonathanstowe** [comment]
That's a Rakudo bug.  I tested last night against a fresh build and it isn't there.

**Comment by AlexDaniel** [comment]
@jonathanstowe I'm a bit confused… is there a ticket or something? This output is from yesterday's HEAD.

**Comment by jonathanstowe** [comment]
Hmm that's way weird, I  literally tested this yesterday, got this error, then rebuilt rakudo, deleted the .precomp all round and it went away,

I'll roll back the change in Lumberjack that assumed the precomp bugs went away.

**Comment by jonathanstowe** [comment]
The underlying bug is https://github.com/rakudo/rakudo/issues/2620 which I moved from RT a few weeks ago, it's been there for a long time.

**Comment by jonathanstowe** [comment]
This is fixed by the https://github.com/jonathanstowe/Lumberjack/tree/v0.0.8  tests okay but I'll leave it for someone else to test as well as I thought I had fixed the original problem and clearly hadn't.
