### ISSUE TITLE
YAML::Parser::LibYAML

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#5]
Module [YAML::Parser::LibYAML](https://modules.perl6.org/dist/YAML::Parser::LibYAML) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by JJ** [comment]
Fails test 

```
Cannot locate native library '/home/jmerelo/progs/forks/perl6/perl6-libyaml/resources/lib/libyamlwrap.so': /home/jmerelo/progs/forks/perl6/perl6-libyaml/resources/lib/libyamlwrap.so: cannot open shared object file: No such file or directory
  in method setup at /home/jmerelo/.rakudobrew/moar-2018.03/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 290
  in method CALL-ME at /home/jmerelo/.rakudobrew/moar-2018.03/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 577
  in sub yaml-parse at /home/jmerelo/progs/forks/perl6/perl6-libyaml/lib/YAML/Parser/LibYAML.pm6 (YAML::Parser::LibYAML) line 153
  in block <unit> at t/00-gauntlet.t line 18
```

**Comment by JJ** [comment]
It's failing because it needs an additional zef install . step, which is not normally needed. Added to the instructions, but the module is basically OK. PR: /tony-o/perl6-libyaml#3

**Comment by Xliff** [comment]
Module is failing its install for me. I am on the latest Kubuntu. Error message is as follows: 

```
$ src/build.sh
gcc: error: libyaml_wrap.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: libyaml_wrap.o: No such file or directory
gcc: error: unrecognized command line option ‘-W1,-soname,libyaml_wrap.so.1’
If you're running locally you may need to add this dir to LD_LIBRARY_PATH
  to do that, run: export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/cbwood/Projects/unbitrot/perl6-libyaml"
```

The problem here is that the file to be compiled is called "yamlwrap.c", not "libyaml_wrap.c" as referenced in src/build.sh:

```
gcc -c -fPIC libyaml_wrap.c -o libyaml_wrap.o
```

Also, this line fails on Debian systems:

```
gcc -shared -W1,-soname,libyaml_wrap.so.1 -lyaml -o libyaml_wrap.so.1.0.0 libyaml_wrap.o
```
