### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#518]
Module [SSL](https://modules.perl6.org/dist/SSL) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: SSL
===> Found: SSL [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: SSL to /home/alex/Blin/data/zef-data/tmp/1549579675.18439.9069/openssl.git
===> Extraction [OK]: SSL to /home/alex/Blin/data/zef-data/store/openssl.git
===> Testing: SSL
Use of the 'unpack' method is experimental; please 'use experimental :pack'
  in block <unit> at t/basic.t line 18

t/basic.t ... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 11/11 subtests 
Use of the 'unpack' method is experimental; please 'use experimental :pack'
  in block <unit> at t/binary.t line 17

t/binary.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 10/10 subtests 

Test Summary Report
-------------------
t/basic.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 11 tests but ran 0.
t/binary.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 10 tests but ran 0.
Files=2, Tests=0,  6 wallclock secs ( 0.03 usr  0.01 sys +  4.97 cusr  0.20 csys =  5.21 CPU)
Result: FAIL
===> Testing [FAIL]: SSL
Failed to get passing tests, but continuing with --force-test
===> Installing: SSL
===> Install [OK] for SSL

````````````````````````````````````````````````````````

Ping @grondilu

Previous ticket: #69

**Comment by jonathanstowe** [comment]
Leaving aside the pack thing there is an additional problem:

```
1..11
ok 1 - MD4
ok 2 - MD5
dgst: Unknown digest sha
dgst: Use -help for summary.
not ok 3 - SHA-0
# Failed test 'SHA-0'
# at t/basic.t line 21
# expected: ''
#      got: 'c199f2a81ed83faed327a53da5d703533850c635'
ok 4 - SHA-1
ok 5 - SHA-224
ok 6 - SHA-256
ok 7 - SHA-384
ok 8 - SHA-512
ok 9 - RIPEMD-160
ok 10 - WHIRLPOOL
ok 11 - SHA-256 with a unicode string
# Looks like you failed 1 test of 11
```

And

```
1..10
ok 1 - MD4
ok 2 - MD5
dgst: Unknown digest sha
dgst: Use -help for summary.
not ok 3 - SHA-0
# Failed test 'SHA-0'
# at t/binary.t line 21
# expected: ''
#      got: 'd486a442ec06dd32b85adc1b3fe5fc6a3b9faa57'
ok 4 - SHA-1
ok 5 - SHA-224
ok 6 - SHA-256
ok 7 - SHA-384
ok 8 - SHA-512
ok 9 - RIPEMD-160
ok 10 - WHIRLPOOL
# Looks like you failed 1 test of 10
```

Which is more of a problem with the way the test is being constructed  (and the version of openssl) than the module itself.  I'll PR a fix.

**Comment by jonathanstowe** [comment]
I also rolled up the earlier PR regarding ```experimental```
