### ISSUE TITLE
Sprockets

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#520]
Module [Sprockets](https://modules.perl6.org/dist/Sprockets) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Sprockets
===> Found: Sprockets:auth<github:vendethiel> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Sprockets:auth<github:vendethiel> to /home/alex/Blin/data/zef-data/tmp/1549579818.22903.3376/Sprockets.pl.git
===> Extraction [OK]: Sprockets to /home/alex/Blin/data/zef-data/store/Sprockets.pl.git
===> Testing: Sprockets:auth<github:vendethiel>
Cannot invoke this object (REPR: Null; VMNull)
  in sub temporary-filename at /home/alex/Blin/data/zef-data/store/Sprockets.pl.git/405f30ccac135394ce2be1325ad647ae01af516a/lib/Sprockets/Filter.pm6 (Sprockets::Filter) line 12
  in sub  at /home/alex/Blin/data/zef-data/store/Sprockets.pl.git/405f30ccac135394ce2be1325ad647ae01af516a/lib/Sprockets/Filter.pm6 (Sprockets::Filter) line 19
  in sub apply-filters at /home/alex/Blin/data/zef-data/store/Sprockets.pl.git/405f30ccac135394ce2be1325ad647ae01af516a/lib/Sprockets/Filter.pm6 (Sprockets::Filter) line 33
  in method Str at /home/alex/Blin/data/zef-data/store/Sprockets.pl.git/405f30ccac135394ce2be1325ad647ae01af516a/lib/Sprockets/File.pm6 (Sprockets::File) line 10
  in block <unit> at t/file.t line 12

# Looks like you planned 2 tests, but ran 1
t/file.t ..... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/2 subtests 
t/locator.t .. ok

Test Summary Report
-------------------
t/file.t   (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 1.
Files=2, Tests=7,  7 wallclock secs ( 0.04 usr  0.00 sys +  6.16 cusr  0.49 csys =  6.69 CPU)
Result: FAIL
===> Testing [FAIL]: Sprockets:auth<github:vendethiel>
Failed to get passing tests, but continuing with --force-test
===> Installing: Sprockets:auth<github:vendethiel>
===> Install [OK] for Sprockets:auth<github:vendethiel>

````````````````````````````````````````````````````````

Ping @vendethiel

Previous ticket: #58

**Comment by vendethiel** [comment]
I'll take a look.

**Comment by vendethiel** [comment]
OK, it's really weird. if I remove the call to `temporary-filename`, I get the several failures (in order when I remove the previous failures):
 - same error [an `open` call](https://github.com/vendethiel/Sprockets.pl/blob/master/lib/Sprockets/Filter.pm6#L20)
 - then it's the [`EVAL` call](https://github.com/vendethiel/Sprockets.pl/blob/master/lib/Sprockets/Filter.pm6#L23)
 - [`slurp` is the next candidate](https://github.com/vendethiel/Sprockets.pl/blob/master/lib/Sprockets/Filter.pm6#L26)
 - and finally, [`unlink`](https://github.com/vendethiel/Sprockets.pl/blob/master/lib/Sprockets/Filter.pm6#L27)

All of these do I/O except `EVAL` (which can).
I tried to isolate the `my $*OUT` into a block of its own (+ `EVAL`) but that doesn't fix it. Neither does using `temp` instead of `my`.

I have *zero idea* what's going on, but I'm not sure it's a bug on my side.

**Comment by vendethiel** [comment]
Works on latest (on my machine™).
