### ISSUE TITLE
Terminal::Print

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#526]
Module [Terminal::Print](https://modules.perl6.org/dist/Terminal::Print) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Terminal::Print
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
===> Found: Terminal::Print:ver<0.94> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Terminal::Print:ver<0.94> to /home/alex/Blin/data/zef-data/tmp/1549582418.32671.9895/Terminal-Print.git
===> Extraction [OK]: Terminal::Print to /home/alex/Blin/data/zef-data/store/Terminal-Print.git
===> Testing: Terminal::Print:ver<0.94>
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "screen.xterm-256color"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
===SORRY!===
Please update @valid-terminals with your desired TERM ('rxvt', is it?) and submit a PR if it works
t/00-basics.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!===
Please update @valid-terminals with your desired TERM ('rxvt', is it?) and submit a PR if it works
t/10-grid.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!===
Please update @valid-terminals with your desired TERM ('rxvt', is it?) and submit a PR if it works
t/11-golf.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

Test Summary Report
-------------------
t/00-basics.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/10-grid.t  (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/11-golf.t  (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=3, Tests=0, 17 wallclock secs ( 0.03 usr  0.00 sys + 10.76 cusr  1.60 csys = 12.39 CPU)
Result: FAIL
===> Testing [FAIL]: Terminal::Print:ver<0.94>
Failed to get passing tests, but continuing with --force-test
===> Installing: Terminal::Print:ver<0.94>
===> Install [FAIL] for Terminal::Print:ver<0.94>: ===SORRY!===
Please update @valid-terminals with your desired TERM ('rxvt', is it?) and submit a PR if it works

===SORRY!===
Please update @valid-terminals with your desired TERM ('rxvt', is it?) and submit a PR if it works


````````````````````````````````````````````````````````

Ping @ab5tract

**Comment by JJ** [comment]
I don't know if it's worth the while to fix this. It's got 3 PRs sent, and no changes for 7 months.

**Comment by JJ** [comment]
I have [forked it](https://github.com/JJ/Terminal-Print) and released it to the ecosystem with a bumped up version. jmp works now with the new version, after it's installed: #551

**Comment by AlexDaniel** [comment]
I'm looking here:
https://github.com/JJ/Terminal-Print/blob/f35f679e403e794250d46b273da2ab2d9a417930/lib/Terminal/Print/Commands.pm6#L27

Is there any reason why it has to run something in shell?

**Comment by JJ** [comment]
It's using tput; not using it would imply refactoring.

**Comment by AlexDaniel** [comment]
yes but can't you use `tput` with `run`?

**Comment by JJ** [comment]
Ah, I see what you mean. Let me try that.

**Comment by jonathanstowe** [comment]
could it be made to use the termios module  with hard coded capability values (assuming they are fairly common capabilities?)

**Comment by jonathanstowe** [comment]
Or help me make Term::Cap useable :-)

**Comment by JJ** [comment]
I don't think [that's trivial](https://github.com/krunen/term-termios), but once we have forked it, I guess we could as well do that.
Anyway, the new version fixes the particular issues raised here, just a matter of adding stuff to the whitelist. Mid-term roadmap could go there, but who knows.
