### ISSUE TITLE
TOML

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#53]
Module [TOML](https://modules.perl6.org/dist/TOML) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by lizmat** [comment]
It appears that `go` must be installed for testing.  I did not try to install `go`.

**Comment by AlexDaniel** [comment]
I installed `golang-toml-dev` debian package but got this when installing the module:
```
===> Searching for: TOML
===> Extraction: Failed to find a META6.json file for TOML:ver<0.3.1.alpha>:auth<Mouq> -- failure is likely
===> Testing: TOML:ver<0.3.1.alpha>:auth<Mouq>
===> Testing [OK] for TOML:ver<0.3.1.alpha>:auth<Mouq>
===> Installing: TOML:ver<0.3.1.alpha>:auth<Mouq>
===> Install [FAIL] for TOML:ver<0.3.1.alpha>:auth<Mouq>: Failed to open file /home/alex/.zef/store/toml-pm6.git/287feac8aaa8055853a9de74e3b5b14c3055465f/lib/TOML/Grammar.pm: No such file or directory
Failed to open file /home/alex/.zef/store/toml-pm6.git/287feac8aaa8055853a9de74e3b5b14c3055465f/lib/TOML/Grammar.pm: No such file or directory
  in any  at /home/alex/.perl6/precomp/77304019A999E1909A325EAEA8E71DD08236CE6D/A1/A1842D1696A2F21CABF8EBE1E3566CAC25B3D05B line 1
  in block  at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/A1842D1696A2F21CABF8EBE1E3566CAC25B3D05B (Zef::Client) line 572
  in any  at /home/alex/.perl6/precomp/77304019A999E1909A325EAEA8E71DD08236CE6D/A1/A1842D1696A2F21CABF8EBE1E3566CAC25B3D05B line 1
  in block  at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/A1842D1696A2F21CABF8EBE1E3566CAC25B3D05B (Zef::Client) line 580
  in block  at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/A1842D1696A2F21CABF8EBE1E3566CAC25B3D05B (Zef::Client) line 546
  in sub  at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/A1842D1696A2F21CABF8EBE1E3566CAC25B3D05B (Zef::Client) line 536
  in method install at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/A1842D1696A2F21CABF8EBE1E3566CAC25B3D05B (Zef::Client) line 617
  in sub MAIN at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/C88E534CF19042FCCA7532BA5F29A52D7C05B892 (Zef::CLI) line 152
  in block <unit> at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/resources/2021D7B844831A552D16A8DBA84764111271B1E6 line 3
  in sub MAIN at /home/alex/.rakudobrew/bin/../moar-master/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/alex/.rakudobrew/bin/../moar-master/install/share/perl6/site/bin/zef line 2
```

**Comment by Altai-man** [comment]
@AlexDaniel this one is simple: in META it has `.pm` extension, but real files are `.pm6`, so it cannot be found. There are tons of PRs that fix it: https://github.com/Mouq/toml-pm6/pulls dated back to 2017, but no luck to see answer from the author, unfortunately.

**Comment by AlexDaniel** [comment]
Ah. OK.
