### ISSUE TITLE
Unicode::GCB

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#538]
Module [Unicode::GCB](https://modules.perl6.org/dist/Unicode::GCB) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Unicode::GCB
===> Found: Unicode::GCB:ver<0.2.1>:auth<github:cygx> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Unicode::GCB:ver<0.2.1>:auth<github:cygx> to /home/alex/Blin/data/zef-data/tmp/1549579903.25535.5173/p6-unicode-gcb.git
===> Extraction [OK]: Unicode::GCB to /home/alex/Blin/data/zef-data/store/p6-unicode-gcb.git
===> Testing: Unicode::GCB:ver<0.2.1>:auth<github:cygx>
# Failed test at t/01-sanity.t line 14
# Failed test at t/01-sanity.t line 15
# Looks like you failed 2 tests of 4
t/01-sanity.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/4 subtests 

Test Summary Report
-------------------
t/01-sanity.t (Wstat: 512 Tests: 4 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 2
Files=1, Tests=4,  4 wallclock secs ( 0.03 usr  0.00 sys +  2.68 cusr  0.17 csys =  2.88 CPU)
Result: FAIL
===> Testing [FAIL]: Unicode::GCB:ver<0.2.1>:auth<github:cygx>
Failed to get passing tests, but continuing with --force-test
===> Installing: Unicode::GCB:ver<0.2.1>:auth<github:cygx>
===> Install [OK] for Unicode::GCB:ver<0.2.1>:auth<github:cygx>

````````````````````````````````````````````````````````

Ping @cygx

**Comment by cygx** [comment]
I added some tests and finalle merged the unicode11 branch that had been sitting around [since October](https://github.com/cygx/p6-unicode-gcb/issues/1).

I guess I shouldn't close this issue manually, but wait until that's done automatically?

**Comment by AlexDaniel** [comment]
Yeah, I'll retest all modules tomorrow and it'll be closed.
