### ISSUE TITLE
YAML

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#546]
Module [YAML](https://modules.perl6.org/dist/YAML) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: YAML
===> Found: YAML [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: YAML to /home/alex/Blin/data/zef-data/tmp/1549580834.21072.9817/yaml-pm6.git
===> Extraction [OK]: YAML to /home/alex/Blin/data/zef-data/store/yaml-pm6.git
===> Testing: YAML
===SORRY!===
Could not find TestML::Runner::TAP at line 1 in:
    file#/home/alex/Blin/data/zef-data/store/yaml-pm6.git/6c6c88e25ccd9e80c6736e84dd0f1df6a45175ab
    file#/home/alex/Blin/data/zef-data/store/yaml-pm6.git/6c6c88e25ccd9e80c6736e84dd0f1df6a45175ab/lib
    file#/home/alex/Blin/data/zef-data/store/yaml-pm6.git/6c6c88e25ccd9e80c6736e84dd0f1df6a45175ab/data/zef/lib
    inst#/home/alex/Blin/installed/TestML_0.2.0
    inst#/home/alex/.perl6
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/site
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/vendor
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6
    ap#
    nqp#
    perl5#
t/dump.t ..... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!===
Could not find TestML::Runner::TAP at line 1 in:
    file#/home/alex/Blin/data/zef-data/store/yaml-pm6.git/6c6c88e25ccd9e80c6736e84dd0f1df6a45175ab
    file#/home/alex/Blin/data/zef-data/store/yaml-pm6.git/6c6c88e25ccd9e80c6736e84dd0f1df6a45175ab/lib
    file#/home/alex/Blin/data/zef-data/store/yaml-pm6.git/6c6c88e25ccd9e80c6736e84dd0f1df6a45175ab/data/zef/lib
    inst#/home/alex/Blin/installed/TestML_0.2.0
    inst#/home/alex/.perl6
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/site
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/vendor
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6
    ap#
    nqp#
    perl5#
t/fail.t ..... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
===SORRY!===
Could not find TestML::Runner::TAP at line 1 in:
    file#/home/alex/Blin/data/zef-data/store/yaml-pm6.git/6c6c88e25ccd9e80c6736e84dd0f1df6a45175ab
    file#/home/alex/Blin/data/zef-data/store/yaml-pm6.git/6c6c88e25ccd9e80c6736e84dd0f1df6a45175ab/lib
    file#/home/alex/Blin/data/zef-data/store/yaml-pm6.git/6c6c88e25ccd9e80c6736e84dd0f1df6a45175ab/data/zef/lib
    inst#/home/alex/Blin/installed/TestML_0.2.0
    inst#/home/alex/.perl6
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/site
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6/vendor
    inst#/tmp/whateverable/rakudo-moar/1ff9b14e8903d77f066f7c2673ea59d6ad7f4aa6/share/perl6
    ap#
    nqp#
    perl5#
t/strings.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

Test Summary Report
-------------------
t/dump.t   (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/fail.t   (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/strings.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=3, Tests=0,  1 wallclock secs ( 0.04 usr  0.01 sys +  1.18 cusr  0.13 csys =  1.36 CPU)
Result: FAIL
===> Testing [FAIL]: YAML
Failed to get passing tests, but continuing with --force-test
===> Installing: YAML
===> Install [OK] for YAML

````````````````````````````````````````````````````````

Ping @perl6-community-modules

Previous ticket: #6

**Comment by jonathanstowe** [comment]
There is an initial dependency issue with TestML - I've picked that one up separately.

**Comment by jonathanstowe** [comment]
I've fixed the initial problem with the TestML but there may still be a problem that isn't covered by its own tests.  Looking

**Comment by jonathanstowe** [comment]
Ooh no I tell a lie.  Hadn't accounted for the slight change in TestML

**Comment by jonathanstowe** [comment]
Fixed with the https://github.com/perl6-community-modules/yaml-pm6/commit/ad79e3e35145c95a14f3987d93e5a869243aa3cb and repair of TestML

**Comment by jonathanstowe** [comment]
I'd cocked up the META.list entry for TesrML  it should be good now
