### ISSUE TITLE
jmp

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#551]
Module [jmp](https://modules.perl6.org/dist/jmp) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: jmp
===SORRY!===
Please update @valid-terminals with your desired TERM ('rxvt', is it?) and submit a PR if it works

===> Found: jmp:ver<3>:auth<github:nige123> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: jmp:ver<3>:auth<github:nige123> to /home/alex/Blin/data/zef-data/tmp/1549583154.15988.7152/jmp.nigelhamilton.com.git
===> Extraction [OK]: jmp to /home/alex/Blin/data/zef-data/store/jmp.nigelhamilton.com.git
===> Testing: jmp:ver<3>:auth<github:nige123>
# Failed test 'JMP module can be use-d ok'
# at t/00-load.t line 6
# ===SORRY!===
# Please update @valid-terminals with your desired TERM ('rxvt', is it?) and submit a PR if it works
# 
# Failed test 'JMP::UI module can be use-d ok'
# at t/00-load.t line 14
# ===SORRY!===
# Please update @valid-terminals with your desired TERM ('rxvt', is it?) and submit a PR if it works
# 
# Looks like you failed 2 tests of 11
t/00-load.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/11 subtests 
t/meta.t ..... ok

Test Summary Report
-------------------
t/00-load.t (Wstat: 512 Tests: 11 Failed: 2)
  Failed tests:  1, 8
  Non-zero exit status: 2
Files=2, Tests=12, 29 wallclock secs ( 0.04 usr  0.01 sys + 20.49 cusr  1.48 csys = 22.02 CPU)
Result: FAIL
===> Testing [FAIL]: jmp:ver<3>:auth<github:nige123>
Failed to get passing tests, but continuing with --force-test
===> Installing: jmp:ver<3>:auth<github:nige123>
===> Install [FAIL] for jmp:ver<3>:auth<github:nige123>: ===SORRY!===
Please update @valid-terminals with your desired TERM ('rxvt', is it?) and submit a PR if it works


````````````````````````````````````````````````````````

Ping @nige123

**Comment by JJ** [comment]
Fails in rxvt due to #526
