### ISSUE TITLE
Cache::Async

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#556]
Module [Cache::Async](https://modules.perl6.org/dist/Cache::Async) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Cache::Async
===> Found: Cache::Async:ver<0.1.3> [via Zef::Repository::Ecosystems<cpan>]
===> Fetching [OK]: Cache::Async:ver<0.1.3> to /home/alex/Blin/data/zef-data/tmp/1549727906.3895.7150/perl6-cache-async-0.1.3.tar.gz
===> Extraction [OK]: Cache::Async to /home/alex/Blin/data/zef-data/store/perl6-cache-async-0.1.3.tar.gz
===> Testing: Cache::Async:ver<0.1.3>
t/00-meta.t ............ ok
t/01-basics.t .......... ok
t/02-async.t ........... ok
# Failed test 'pausing between gets evicts the older entries'
# at t/03-expiry.t line 90
# expected: 'ABCDBA'
#      got: 'ABCDCBA'
# Looks like you failed 1 test of 12
t/03-expiry.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/12 subtests 
t/04-exceptions.t ...... ok
t/05-monitoring.t ...... ok
t/06-slurpies.t ........ ok
t/07-async-producer.t .. ok
t/08-refreshing.t ...... ok

Test Summary Report
-------------------
t/03-expiry.t        (Wstat: 256 Tests: 12 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=9, Tests=63, 17 wallclock secs ( 0.08 usr  0.01 sys + 12.03 cusr  0.70 csys = 12.82 CPU)
Result: FAIL
===> Testing [FAIL]: Cache::Async:ver<0.1.3>
Failed to get passing tests, but continuing with --force-test
===> Installing: Cache::Async:ver<0.1.3>
===> Install [OK] for Cache::Async:ver<0.1.3>

````````````````````````````````````````````````````````

Ping @robertlemmen

**Comment by JJ** [comment]
The issue has been sent, although actually I didn't find that error above...
