### ISSUE TITLE
HTTP::Server::Middleware::JSON

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#559]
Module [HTTP::Server::Middleware::JSON](https://modules.perl6.org/dist/HTTP::Server::Middleware::JSON) cannot be installed (`Flapper`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: HTTP::Server::Middleware::JSON
===> Found: HTTP::Server::Middleware::JSON:ver<0.0.1>:auth<github:tony-o> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: HTTP::Server::Middleware::JSON:ver<0.0.1>:auth<github:tony-o> to /home/alex/Blin/data/zef-data/tmp/1549726829.10845.1282/perl6-http-server-middleware-json.git
===> Extraction [OK]: HTTP::Server::Middleware::JSON to /home/alex/Blin/data/zef-data/store/perl6-http-server-middleware-json.git
===> Testing: HTTP::Server::Middleware::JSON:ver<0.0.1>:auth<github:tony-o>
# Failed test 'Not parsed'
# at t/00-basic.t line 45
# Failed test 'Attempt parse and fail with default error handler'
# at t/00-basic.t line 49
# Failed test 'Attempt parse and fail with custom error handler'
# at t/00-basic.t line 56
# Looks like you failed 3 tests of 5
t/00-basic.t .. 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/5 subtests 

Test Summary Report
-------------------
t/00-basic.t (Wstat: 768 Tests: 5 Failed: 3)
  Failed tests:  1, 4-5
  Non-zero exit status: 3
Files=1, Tests=5,  6 wallclock secs ( 0.03 usr  0.00 sys +  2.88 cusr  0.16 csys =  3.07 CPU)
Result: FAIL
===> Testing [FAIL]: HTTP::Server::Middleware::JSON:ver<0.0.1>:auth<github:tony-o>
Failed to get passing tests, but continuing with --force-test
===> Installing: HTTP::Server::Middleware::JSON:ver<0.0.1>:auth<github:tony-o>
===> Install [OK] for HTTP::Server::Middleware::JSON:ver<0.0.1>:auth<github:tony-o>

````````````````````````````````````````````````````````

Ping @tony-o

**Comment by shlomif** [comment]
@AlexDaniel : this seems fine here.
