### ISSUE TITLE
Java::Generate

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#561]
Module [Java::Generate](https://modules.perl6.org/dist/Java::Generate) cannot be installed (`Flapper`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Java::Generate
===> Found: Java::Generate:ver<1.0.0> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Java::Generate:ver<1.0.0> to /home/alex/Blin/data/zef-data/tmp/1549725693.11268.3010/perl6-Java-Generate.git
===> Extraction [OK]: Java::Generate to /home/alex/Blin/data/zef-data/store/perl6-Java-Generate.git
===> Testing: Java::Generate:ver<1.0.0>
===SORRY!===
finish_code_object
t/01-hello-world.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
t/02-literal.t ...... ok
t/03-operators.t .... ok
t/04-interface.t .... ok
t/05-class.t ........ ok
t/06-variables.t .... ok
t/07-statement.t .... ok
t/08-generics.t ..... ok
t/09-comp-unit.t .... ok

Test Summary Report
-------------------
t/01-hello-world.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=9, Tests=80, 39 wallclock secs ( 0.05 usr  0.02 sys + 33.88 cusr  2.08 csys = 36.03 CPU)
Result: FAIL
===> Testing [FAIL]: Java::Generate:ver<1.0.0>
Failed to get passing tests, but continuing with --force-test
===> Installing: Java::Generate:ver<1.0.0>
===> Install [OK] for Java::Generate:ver<1.0.0>

````````````````````````````````````````````````````````

Ping @Altai-man

Previous ticket: #163

**Comment by Altai-man** [comment]
This seem like a rakudobug to me, a weird one.
I can
```
➜  perl6-Java-Generate git:(master) prove --jobs=1 -e "perl6-m -Ilib -It" t/
t/01-hello-world.t .. ok   
t/02-literal.t ...... ok     
t/03-operators.t .... ok     
t/04-interface.t .... ok   
t/05-class.t ........ ok   
t/06-variables.t .... ok   
t/07-statement.t .... ok     
t/08-generics.t ..... ok   
t/09-comp-unit.t .... ok   
All tests successful.
Files=9, Tests=81, 10 wallclock secs ( 0.04 usr  0.01 sys + 15.19 cusr  1.18 csys = 16.42 CPU)
Result: PASS
➜  perl6-Java-Generate git:(master) 
```
and it installs just fine with `zef`.

The whole module is a simple bunch of classes that generate source code, no magic to fail every time... So marking it as `works for me` and `rakudobug`.
