### ISSUE TITLE
Readline

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#564]
Module [Readline](https://modules.perl6.org/dist/Readline) cannot be installed (`Fail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Readline
===> Found: Readline:ver<0.1.4>:auth<github:drforr> [via Zef::Repository::Ecosystems<p6c>]
===> Fetching [OK]: Readline:ver<0.1.4>:auth<github:drforr> to /home/alex/Blin/data/zef-data/tmp/1549725872.15498.7306/perl6-readline.git
===> Extraction [OK]: Readline to /home/alex/Blin/data/zef-data/store/perl6-readline.git
===> Testing: Readline:ver<0.1.4>:auth<github:drforr>
t/01-load.t .. ok
    # Failed test 'funmap-names lives'
    # at t/02-base.t line 99
    # Don't know how many elements a C array returned from a library
    # Looks like you failed 1 test of 1
# Failed test 'funmap'
# at t/02-base.t line 91
    # Failed test 'history-list lives'
    # at t/02-base.t line 250
    # Don't know how many elements a C array returned from a library
    # Failed test 'history-tokenize lives'
    # at t/02-base.t line 289
    # Don't know how many elements a C array returned from a library
    # Looks like you failed 2 tests of 25
# Failed test 'history'
# at t/02-base.t line 206
# Looks like you failed 2 tests of 17
t/02-base.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/17 subtests 

Test Summary Report
-------------------
t/02-base.t (Wstat: 512 Tests: 17 Failed: 2)
  Failed tests:  8, 14
  Non-zero exit status: 2
Files=2, Tests=18, 31 wallclock secs ( 0.05 usr  0.01 sys + 30.90 cusr  0.46 csys = 31.42 CPU)
Result: FAIL
===> Testing [FAIL]: Readline:ver<0.1.4>:auth<github:drforr>
Failed to get passing tests, but continuing with --force-test
===> Installing: Readline:ver<0.1.4>:auth<github:drforr>
===> Install [OK] for Readline:ver<0.1.4>:auth<github:drforr>

````````````````````````````````````````````````````````

Ping @drforr

Previous ticket: #75

**Comment by Kaiepi** [comment]
None of the tests fail on my system
