### ISSUE TITLE
Sparrowdo::VSTS::YAML::Nuget

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#569]
Module [Sparrowdo::VSTS::YAML::Nuget](https://modules.perl6.org/dist/Sparrowdo::VSTS::YAML::Nuget) cannot be installed (`ZefFailure`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
===> Searching for: Sparrowdo::VSTS::YAML::Nuget
«timed out after 600 seconds»
````````````````````````````````````````````````````````

Ping @melezhik

**Comment by melezhik** [comment]
Hi! Sorry for delay. I'd like to take care about that. One thing. Sparrow is under massive rework being ported to Perl6. This will touch  Sparrowdo modules as well. Let's put it on hold till the first Sparrow6 release. What do you guys think?

**Comment by Altai-man** [comment]
I think there is no problem to wait as long as it is a known issue being worked on.

**Comment by AlexDaniel** [comment]
It was closed automatically because the module passed all of its tests.

List of related modules:
```
Sparrowdo – OK
Sparrowdo::Archive – OK
Sparrowdo::Azure::Web::Cert – OK
Sparrowdo::Chef::Client – OK
Sparrowdo::Chef::Manager – OK
Sparrowdo::Cordova::OSx::Build – OK
Sparrowdo::Cordova::OSx::Fortify – OK
Sparrowdo::Cpanm::GitHub – OK
Sparrowdo::Cpm – OK
Sparrowdo::Goss – OK
Sparrowdo::Nginx – OK
Sparrowdo::Prometheus – OK
Sparrowdo::Rakudo – OK
Sparrowdo::RemoteFile – OK
Sparrowdo::Ruby::Bundler – OK
Sparrowdo::Rvm – OK
Sparrowdo::Sparrow::Update – OK
Sparrowdo::VSTS::YAML::Angular::Build – OK
Sparrowdo::VSTS::YAML::Artifact – OK
Sparrowdo::VSTS::YAML::Build – OK
Sparrowdo::VSTS::YAML::Build::Assembly::Patch – OK
Sparrowdo::VSTS::YAML::Cordova – OK
Sparrowdo::VSTS::YAML::DotNet – OK
Sparrowdo::VSTS::YAML::MsBuild – OK
Sparrowdo::VSTS::YAML::Nuget – OK
Sparrowdo::VSTS::YAML::Nuget::Build – OK
Sparrowdo::VSTS::YAML::Solution – OK
Sparrowdo::VSTS::YAML::Update::Azure::SSL – OK
```

There's nothing to be done here as far as I'm concerned. The goal of this repo is to fix modules that don't install cleanly.
