### ISSUE TITLE
Numeric::Nearest

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#590]
Module [Numeric::Nearest](https://modules.perl6.org/dist/Numeric::Nearest) cannot be installed (`AlwaysFail`), perhaps it has some failing tests.

* Tickets are opened/closed in this repo automatically (though not immediately).
* If you can **install the module without any problems**, add `works for me` label, leave a comment saying that it works for you and mention any details that you feel are important.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). Also try to update [this wiki page](https://github.com/perl6/ecosystem-unbitrot/wiki).
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).
* **Once you are done**, [search for a next ticket](https://github.com/perl6/ecosystem-unbitrot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22PR+sent%22+-label%3A%22deprecated+module%22+-label%3A%22native+dependency%22).

If you can't self-assign yourself or attach a label, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

Output:

````````````````````````````````````````````````````````
===> Searching for: Numeric::Nearest
===> Found: Numeric::Nearest:ver<0.5.0> [via Zef::Repository::Ecosystems<cpan>]
===> Fetching [OK]: Numeric::Nearest:ver<0.5.0> to /home/alex/Blin/data/zef-data/tmp/1551234916.2029.7067/Numeric-Nearest-0.5.0.tar.gz
===> Extraction [OK]: Numeric::Nearest to /home/alex/Blin/data/zef-data/store/Numeric-Nearest-0.5.0.tar.gz
===> Testing: Numeric::Nearest:ver<0.5.0>
===SORRY!===
Could not find Test::META at line 3 in:
    file#/home/alex/Blin/data/zef-data/store/Numeric-Nearest-0.5.0.tar.gz/Numeric::Nearest-0.5.0
    file#/home/alex/Blin/data/zef-data/store/Numeric-Nearest-0.5.0.tar.gz/Numeric::Nearest-0.5.0/lib
    file#/home/alex/Blin/data/zef-data/store/Numeric-Nearest-0.5.0.tar.gz/Numeric::Nearest-0.5.0/data/zef/lib
    inst#/home/alex/.perl6
    inst#/tmp/whateverable/rakudo-moar/845433b47f415c73e9e7cdbfd0423a793b829910/share/perl6/site
    inst#/tmp/whateverable/rakudo-moar/845433b47f415c73e9e7cdbfd0423a793b829910/share/perl6/vendor
    inst#/tmp/whateverable/rakudo-moar/845433b47f415c73e9e7cdbfd0423a793b829910/share/perl6
    ap#
    nqp#
    perl5#
t/basic.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

Test Summary Report
-------------------
t/basic.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  1 wallclock secs ( 0.03 usr  0.01 sys +  0.54 cusr  0.44 csys =  1.02 CPU)
Result: FAIL
===> Testing [FAIL]: Numeric::Nearest:ver<0.5.0>
Failed to get passing tests, but continuing with --force-test
===> Installing: Numeric::Nearest:ver<0.5.0>
===> Install [OK] for Numeric::Nearest:ver<0.5.0>

````````````````````````````````````````````````````````

Ping @drclaw1394

**Comment by AlexDaniel** [comment]
This is a simple case of a missing `test-depends` field in META6.json.

**Comment by drclaw1394** [comment]
Just looking at it now. I think you are correct. I've removed Test::META from my local system and I have a failed test.

**Comment by drclaw1394** [comment]
Ok I can't self assign this issue. How do I go about getting it assigned to me?

**Comment by jonathanstowe** [comment]
An alternative is to use a test that  attempts to ```require Test::META``` and skips the test it fails.  See any of my modules for an example.

**Comment by drclaw1394** [comment]
Thanks for the tip. I'll check it out.

**Comment by drclaw1394** [comment]
Updated the META6 file with test-depends field.
