### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by Juniortheone** [perl6/ecosystem-unbitrot#595]
I was installing doxygen but this was the error message I got;
`The following packages have unmet dependencies:
doxygen:Depends:libclang1-3.6 (>= 3.2) but it is not going to be installed
E: Unable to correct problems,you have held broken packages.`
I did some searching and found out that it is not from doxygen but libclang instead.I tried finding a solution to no avail.Any help?

**Comment by AlexDaniel** [comment]
Which perl 6 module were you trying to install?

**Comment by Juniortheone** [comment]
I was trying to install doxygen
