### ISSUE TITLE
YAML

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#6]
Module [YAML](https://modules.perl6.org/dist/YAML) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by jkramer** [comment]
Dependency TestML can't be installed due to a wrong source-url in its META6.json. Sent a PR, corresponding ticket is here: https://github.com/perl6/ecosystem-unbitrot/issues/39

**Comment by ingydotnet** [comment]
I'll take a look at this during the Perl Conference in Glasgow in 2 weeks...

**Comment by AlexDaniel** [comment]
I installed TestML manually and then I was able to install YAML. So it works for me, and will work for others when the PR is merged: https://github.com/ingydotnet/testml-pm6/pull/4
