### ISSUE TITLE
Rabble

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/ecosystem-unbitrot#79]
Module [Rabble](https://modules.perl6.org/dist/Rabble) is failing its tests and/or does not install.

* Please close this issue only if the module **passes its tests and is installable**. One way to test it is to run `zef install MODULENAME`.
* If you can **install the module without any problems**, label this ticket with `works for me` and close the issue.
* If it **needs a native library**, put `native dependency` label, describe what you did to install it and ensure that same instructions are present in the README file of the module (otherwise submit a pull request). If everything is green you can close the issue.
* If the **module is broken**, try to fix it and send a PR. Add `PR sent` label and close the issue.
* If there is a **problem in one of the dependencies**, add `failing dependency` label and write a comment explaining the situation. Leave this ticket open and feel free to work on the corresponding ticket for the failing dependency.
* It is a good idea to **assign yourself** to this ticket if you're working on it (to make sure two or more people are not working on the same ticket at the same time).

If you can't self-assign, attach a label, or close the ticket, please let us know on [#perl6 channel on freenode](https://perl6.org/irc) or just leave a comment here. We will try to give you privileges as fast as possible.

**Comment by bbkr** [comment]
```
$ perl6 -v
This is Rakudo version 2018.06 built on MoarVM version 2018.06
implementing Perl 6.c.

$ prove -e perl6
t/010-Rabble.t ....... ok
t/030-Arithmetic.t ... ok
t/040-Combinators.t .. ok
t/050-Comparators.t .. ok
t/060-IO.t ........... ok
t/070-Shufflers.t .... ok
t/080-StackOps.t ..... ok
All tests successful.
```

**Comment by AlexDaniel** [comment]
From toaster:
```
===> Install [FAIL] for Rabble:ver<0.3.1>: Failed to open file /home/cpan/.zef/store/rabble.git/b65b895e60604421936f2a63ae3f5da0b5207182/lib/Rabble/Math/Arithmetic: No such file or directory
```
I'm not sure what it means.

**Comment by Altai-man** [comment]
It means that here is a thinko at https://github.com/MadcapJake/rabble/blob/master/META6.json#L13
:)
Please, don't just run tests, it often happens that META file itself has some mistake due to which the module is fine, but cannot be installed by users nicely.
Fixed at https://github.com/MadcapJake/rabble/pull/2
